---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/bosh-dns-release
    tag: acceptance-tests-windows

inputs:
  - name: bosh-dns-release
  - name: envs

run:
  path: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-shared.sh

params:
  ENV_NAME: ""
  WINDOWS_OS_VERSION: ""
