[[constraint]]
  name = "github.com/cloudfoundry/bosh-cli"
  version = "2.0.45"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
