---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1

params:
  DATADOG_API_KEY: ~
  DATADOG_ENVIRONMENT_TAG: ~

inputs:
  - name: bosh-dns-release

run:
  path: bosh-dns-release/ci/tasks/test-performance.sh
