---

- type: replace
  path: /instance_groups/0/jobs/-
  value:
    name: configures-handler
    release: dns-acceptance
    properties:
      handler_server_address: ((recursor_ip))
      handler_domain: handler.internal.local.
