---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v10

inputs:
  - name: bbl-state
  - name: bosh-deployment
  - name: bosh-dns-release
  - name: candidate-release
  - name: stemcell
  - name: docker-release

outputs:
  - name: docker-vars

params:
  BBL_STATE_SUBDIRECTORY: test-stress/bbl-state

run:
  path: bosh-dns-release/ci/tasks/test-stress/deploy-docker.sh
