---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5

inputs:
  - name: bbl-state
  - name: bosh-dns-release

params:
  DEPLOYMENTS_OF_100: 10
  PARALLEL_DEPLOYMENTS: 10
  BBL_STATE_SUBDIRECTORY: ~

run:
  path: bosh-dns-release/ci/tasks/test-stress/run-errand.sh
